### ISSUE TITLE
nao compila

### ISSUE THREAD

**Issue by phsilvasantos** [JaedsonBarbosa/NFeFacil#1]
boa noite nao esta compilando da esse erro

Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro		O nó filho "2" foi encerrado prematuramente. Desligando. Informações de diagnóstico poderão ser encontradas nos arquivos em "C:\Users\Paulo\AppData\Local\Temp\" e estarão nomeadas como MSBuild_*.failure.txt. Esse local pode ser alterado por meio da configuração da variável de ambiente MSBUILDDEBUGPATH para um diretório diferente.	Venda (Venda\Venda)

**Comment by phsilvasantos** [comment]
desconsiderar era erro no vs

**Comment by JaedsonBarbosa** [comment]
Oi, sim sim, dado o tamanho do projeto é normal acontecer algum erro na primeira vez.
