### ISSUE TITLE
Desenvolvedor Mobile

### ISSUE THREAD

**Issue by Marcelo3012** [JaedsonBarbosa/NFeFacil#2]
O senhor ainda tem contato e esta programando? E qual contato com desenvolvimento de aplicativo

**Comment by jaedson-barbosa** [comment]
Oi, boa tarde. Sim, estou trabalhando em alguns projetos atualmente com programação, por quê?

**Comment by Marcelo3012** [comment]
Tenho interesse em criar um aplicativo, para versão inicial android, ademais pode se tornar uma futura startup , mas ainda preciso validar a ideia, queria a opinião de um futuro socio, programador também, e como já tive outras ideias e não coloquei em prática e tive essa e outra ideia, vendo um problema coletivo que pode ser resolvido ou aproveitado, decidi nao deixar passar também, e investir, o tempo um pouco maior dessa quarentena, que a gente ta vivendo sem precisar ir para UFPB, para pesquisar a respeito e formentar essa ideia

**Comment by jaedson-barbosa** [comment]
Ah, uma ideia? Hum, legal. Boa sorte, nunca desista dos seus sonhos 😉

**Comment by jaedson-barbosa** [comment]
Bem, agora já faço parte de um projeto de extensão, então meu tempo foi reduzido a 0.
Mas fala aí a ideia, posso dar uma opinião sobre.
